2020-02-22 10:56:09,850 - instabot version: 0.109.0 (bot) - INFO - Instabot version: 0.109.0 Started
2020-02-22 10:56:11,912 - instabot version: 0.109.0 (api_login) - INFO - Recovery from /Users/niels/Documents/instabot/examples/config/dronevlieger_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=d936e783-96b0-4684-b21b-2afb58ecfcf7
- uuid=122b7682-5cd8-41d4-a8db-31a23d014db0
- client_session_id=ce760bb8-9ebc-4bf5-bd41-bfe938ce4a5b
- device_id=android-17757404dd6a9a97
2020-02-22 10:56:11,912 - instabot version: 0.109.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-02-22 10:56:18,368 - instabot version: 0.109.0 (api) - INFO - Logged-in successfully as 'dronevlieger'!
2020-02-22 10:56:40,054 - instabot version: 0.109.0 (multi_script_CLI) - ERROR - list index out of range
Traceback (most recent call last):
  File "multi_script_CLI.py", line 662, in <module>
    menu()
  File "multi_script_CLI.py", line 235, in menu
    menu_like()
  File "multi_script_CLI.py", line 376, in menu_like
    hashtags.append(random.choice(bot.read_list_from_file(hashtag_file)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 277, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
2020-02-22 10:57:24,171 - instabot version: 0.109.0 (multi_script_CLI) - ERROR - list index out of range
Traceback (most recent call last):
  File "multi_script_CLI.py", line 662, in <module>
    menu()
  File "multi_script_CLI.py", line 235, in menu
    menu_like()
  File "multi_script_CLI.py", line 376, in menu_like
    hashtags.append(random.choice(bot.read_list_from_file(hashtag_file)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 277, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
2020-02-22 10:58:01,833 - instabot version: 0.109.0 (multi_script_CLI) - ERROR - list index out of range
Traceback (most recent call last):
  File "multi_script_CLI.py", line 662, in <module>
    menu()
  File "multi_script_CLI.py", line 235, in menu
    menu_like()
  File "multi_script_CLI.py", line 376, in menu_like
    hashtags.append(random.choice(bot.read_list_from_file(hashtag_file)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 277, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
2020-02-22 10:58:13,104 - instabot version: 0.109.0 (bot_like) - INFO - Going to like media with hashtag #dronevlieger.
2020-02-22 10:58:16,924 - instabot version: 0.109.0 (bot_like) - INFO - Going to like 86 medias.
2020-02-22 10:58:49,626 - instabot version: 0.109.0 (bot) - INFO - Total requests: 30
