2020-02-15 19:22:20,145 - instabot version: 0.107.0 (bot) - INFO - Instabot version: 0.107.0 Started
2020-02-15 19:22:20,146 - instabot version: 0.107.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-02-15 19:22:35,796 - instabot version: 0.107.0 (api) - INFO - Logged-in successfully as 'dronevlieger'!
2020-02-15 19:22:35,796 - instabot version: 0.107.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: True
2020-02-15 19:22:48,698 - instabot version: 0.107.0 (api_login) - ERROR - Exception raised: module 'instabot.api.config' has no attribute 'FACE_TRACKER_VERSION'
Traceback (most recent call last):
  File "/Users/niels/Documents/instabot/examples/../instabot/api/api_login.py", line 114, in login_flow
    check_flow.append(self.get_reels_media())
  File "/Users/niels/Documents/instabot/examples/../instabot/api/api.py", line 1589, in get_reels_media
    "FACE_TRACKER_VERSION": config.FACE_TRACKER_VERSION,
AttributeError: module 'instabot.api.config' has no attribute 'FACE_TRACKER_VERSION'

2020-02-15 19:22:48,698 - instabot version: 0.107.0 (bot_follow) - INFO - Follow followers of: fromwhereidrone
2020-02-15 19:22:54,662 - instabot version: 0.107.0 (api) - ERROR - Request returns 429 error!
2020-02-15 19:22:54,662 - instabot version: 0.107.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2020-02-15 19:22:55,611 - instabot version: 0.107.0 (bot) - INFO - Total requests: 16
